<?php
/**
 * @var \Mykhailok\ControllerDemo\Block\View\DemoTemplate $block
 */
$request = $block->getRequest();
?>
<?php if ($block->hasRequestParams(['name', 'lastname','repository_url'])): ?>
    <div class="details">
        <p><?= __('Hello, <strong>%1 %2</strong>', $block->escapeHtml($request->getParam('name')), $block->escapeHtml($request->getParam('lastname'))) ?></p>
        <?php $repositoryUrl = $request->getParam('repository_url'); ?>
        <p><a href="<?= $block->escapeUrl($repositoryUrl) ?>"><?= $block->escapeHtml($repositoryUrl) ?></a></p>
    </div>
<?php else: ?>
    <a href="<?= $block->escapeUrl($block->getUrl('mykhailok_controller_demo/index/forward')) ?>"><?= $block->escapeHtml(__('Forward')) ?></a>
<?php endif; ?>