<?php
/**
 * @var \Mykhailok\ControllerDemo\Block\View\DemoTemplate $block
 */
?>

<?php if ($block->isRequestParams(['name', 'lastname','repository_url'])): ?>
    <div class="details">
        <p>Hello, <strong><?= $block->getRequestParam('name') . ' ' . $block->getRequestParam('lastname') ?></strong>
        </p>
        <?php $repository_url = $block->getRequestParam('repository_url'); ?>
        <p>Your repository: <a href="<?= $repository_url ?>"><?= $repository_url ?></a></p>
    </div>
<?php else: ?>
    <a href="<?= $block->escapeUrl($block->getUrl('mykhailok_controller_demo/index/forward')) ?>">Forward</a>
<?php endif; ?>
