<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<div data-bind="scope:'mykhailok-support-chat'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "mykhailok-support-chat": {
                        "component": "Mykhailok_SupportChat/js/view/chat",
                        "template": "Mykhailok_SupportChat/chat",
                        "action": "/rest/V1/chat-messages/personal-messages"
                    }
                }
            }
        }
    }
</script>
