<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<a href="javascript:void(0);"
   class="mykhailok-support-chat-link toogle-chat chat-link active"
   data-mage-init='{"mykhailok_SupportChat_toggleChat": {}}'
>-</a>
<a href="javascript:void(0);"
   class="mykhailok-support-chat-link open-chat chat-link active"
   data-mage-init='{"mykhailok_SupportChat_openButton": {}}'

><i class="support-chat-icon-chat" aria-hidden="true"><span>Open chat</span></i></a>
