<?php
declare(strict_types=1);

namespace Mykhailok\ControllerDemo\Block\View;

class DemoTemplate extends \Magento\Framework\View\Element\Template
{
    /**
     * @param string $key
     * @return mixed
     */
    public function getRequestParam(string $key)
    {
        return $this->escapeHtml($this->getRequest()->getParam($key));
    }

    /**
     * @param array|string $data
     * @param null $allowedTags
     * @return string
     */
    public function escapeHtml($data, $allowedTags = null)
    {
        return parent::escapeHtml(__($data), $allowedTags); // TODO: Change the autogenerated stub
    }

    /**
     * @param array $params
     * @return bool
     */
    public function isRequestParams(array $params): bool
    {
        $exist = true;
        foreach ($params as $param_name) {
            if ($this->getRequest()->getParam($param_name) === null) {
                $exist = false;
                break;
            }
        }

        return $exist;
    }
}
